### ISSUE TITLE
Username isn't being mapped back to email on user object

### ISSUE THREAD

**Issue by rfrovarp** [ExclamationLabs/connector-zoom#21]
It's being lost through the adapter in constructModel()

**Comment by Stephenglfox** [comment]
We are implementing the change requested in the pull request to look at the __NAME__ attribute for an email address when when the EMAIL attribute is not set.

**Comment by Stephenglfox** [comment]
Fixed in version 4.2.1 as requested

**Comment by Stephenglfox** [comment]
V4.2.1 Fixes this issue.

**Comment by Stephenglfox** [comment]
We published V4.2.1 which fixes this issue.
